# Generated by Django 4.1 on 2024-01-09 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComunidadPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esAdmin', models.BooleanField(default=False)),
                ('observador', models.BooleanField(default=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=50, null=True)),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('ubicacion_geografica', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=30)),
                ('comunidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=50, null=True)),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('usuarioReportador', models.CharField(max_length=20, null=True)),
                ('solucionado', models.CharField(max_length=20, null=True)),
                ('fechaCreado', models.DateField(null=True)),
                ('fechaCierre', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=50, null=True)),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('ubicacion_geografica', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderador', models.BooleanField(default=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.estacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('comunidades', models.ManyToManyField(blank=True, related_name='comunidades', through='Monitoreo.ComunidadPerfil', to='Monitoreo.comunidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=20, null=True)),
                ('tipo_organizacion', models.CharField(choices=[('Supermercado', 'Supermercado'), ('Centro Comunal', 'Centro Comunal'), ('Banco', 'Banco')], max_length=20)),
                ('sucursales', models.ManyToManyField(related_name='sucursales', to='Monitoreo.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=20, null=True)),
                ('tipo_transporte', models.CharField(choices=[('Subterraneo', 'Subterráneo'), ('Ferrocarril', 'Ferrocarril')], max_length=20)),
                ('estacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacion_destino', to='Monitoreo.estacion')),
                ('estacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacion_origen', to='Monitoreo.estacion')),
                ('estaciones_intermedias', models.ManyToManyField(related_name='estaciones_intermedias', to='Monitoreo.estacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comunidadperfil',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.perfil'),
        ),
    ]
