# Generated by Django 5.0 on 2023-12-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineatransporte',
            name='estaciones_intermedias',
            field=models.ManyToManyField(related_name='estaciones_intermedias', to='Monitoreo.estacion'),
        ),
    ]
