# Generated by Django 5.0 on 2024-02-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineatransporte',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='LineaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.lineatransporte')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='lineas',
            field=models.ManyToManyField(blank=True, related_name='lineas', through='Monitoreo.LineaPerfil', to='Monitoreo.lineatransporte'),
        ),
        migrations.CreateModel(
            name='OrganismoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_organismo', models.CharField(choices=[('Entidad prestadora', 'Entidad prestadora'), ('Organismo de Control', 'Organismo de Control')], max_length=20)),
                ('lineas', models.ManyToManyField(related_name='lineas_org', to='Monitoreo.lineatransporte')),
                ('organizaciones', models.ManyToManyField(related_name='organizaciones_org', to='Monitoreo.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.perfil')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='servicios', through='Monitoreo.ServicioPerfil', to='Monitoreo.servicio'),
        ),
    ]
