# Generated by Django 5.0 on 2024-02-05 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0002_lineatransporte_foto_organizacion_foto_lineaperfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='sucursales',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='sucursales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='Monitoreo.sucursal'),
            preserve_default=False,
        ),
    ]
