# Generated by Django 5.0 on 2024-02-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0003_remove_organizacion_sucursales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='sucursales',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizacion', to='Monitoreo.organizacion'),
            preserve_default=False,
        ),
    ]
