# Generated by Django 5.0 on 2023-12-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0003_categoria_servicio_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacionservicio',
            name='linea_transporte',
        ),
    ]
