# Generated by Django 5.0 on 2024-02-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0004_remove_organizacion_sucursales_sucursal_organizacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrestacionServicio',
            new_name='PrestacionServicioEstacion',
        ),
        migrations.CreateModel(
            name='PrestacionServicioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderador', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.sucursal')),
            ],
        ),
    ]
