# Generated by Django 5.0 on 2023-12-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0005_comunidad_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='comunidades',
            field=models.ManyToManyField(blank=True, null=True, related_name='comunidades', to='Monitoreo.comunidad'),
        ),
    ]
