# Generated by Django 5.0 on 2024-02-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0006_rename_moderador_prestacionservicioestacion_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
