# Generated by Django 5.0 on 2023-12-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0006_perfil_comunidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='comunidades',
            field=models.ManyToManyField(blank=True, related_name='comunidades', to='Monitoreo.comunidad'),
        ),
    ]
