# Generated by Django 5.0 on 2023-12-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0007_alter_perfil_comunidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
