# Generated by Django 5.0 on 2024-02-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0008_rename_servicioperfil_servicioperfilestacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
