# Generated by Django 5.0.1 on 2024-02-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0009_sucursal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultima_latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
