# Generated by Django 5.0 on 2024-02-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0009_sucursal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='servicios',
            field=models.ManyToManyField(related_name='servicios', to='Monitoreo.servicio'),
        ),
    ]
