# Generated by Django 5.0 on 2023-12-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0009_perfil_direccion_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='localidad',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
