# Generated by Django 5.0 on 2023-12-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0010_estacion_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='localidad',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
