# Generated by Django 5.0 on 2024-02-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0010_estacion_servicios'),
        ('Monitoreo', '0010_perfil_ultima_latitud_perfil_ultima_longitud'),
    ]

    operations = [
    ]
