# Generated by Django 5.0 on 2024-02-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0011_merge_20240214_1741'),
    ]

    operations = [
        
    ]
