# Generated by Django 5.0 on 2024-02-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0011_merge_20240215_1808'),
    ]

    operations = [
        
    ]
