# Generated by Django 5.0 on 2024-02-16 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0012_remove_estacion_servicios_comunidad_daralta'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='SolicitudComunidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('motivo', models.CharField(max_length=255, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.perfil')),
            ],
        ),
    ]
