# Generated by Django 5.0 on 2024-01-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0012_rename_editor_admincomunidad_rename_admin_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincomunidad',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='control',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='AdminComunidad',
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.DeleteModel(
            name='Miembro',
        ),
    ]
