# Generated by Django 5.0 on 2024-02-15 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0012_remove_estacion_servicios'),
    ]

    operations = [
        
    ]
