# Generated by Django 5.0 on 2024-01-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0011_alter_estacion_localidad'),
        ('Monitoreo', '0012_rename_editor_admincomunidad_rename_admin_control_and_more'),
    ]

    operations = [
    ]
