# Generated by Django 5.0 on 2024-02-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0013_remove_comunidad_daralta_solicitudcomunidad'),
        ('Monitoreo', '0013_solicitudcomunidad'),
    ]

    operations = [
    ]
