# Generated by Django 5.0 on 2024-01-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0013_remove_admincomunidad_group_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='comunidades',
        ),
    ]
