# Generated by Django 5.0 on 2024-02-21 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0014_merge_20240217_0110'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria_alternativa', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=255, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.categoria')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.perfil')),
            ],
        ),
    ]
