# Generated by Django 5.0 on 2024-01-04 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0014_remove_perfil_comunidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ComunidadPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esAdmin', models.BooleanField(default=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.comunidad')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoreo.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='comunidades',
            field=models.ManyToManyField(blank=True, related_name='comunidades', through='Monitoreo.ComunidadPerfil', to='Monitoreo.comunidad'),
        ),
    ]
