# Generated by Django 5.0 on 2024-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0017_remove_estacion_servicios_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='solicitudservicio',
            name='categoria_alternativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
