# Generated by Django 5.0 on 2024-02-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0020_remove_estacion_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismoexterno',
            name='lineas',
            field=models.ManyToManyField(blank=True, related_name='lineas_org', to='Monitoreo.lineatransporte'),
        ),
        migrations.AlterField(
            model_name='organismoexterno',
            name='organizaciones',
            field=models.ManyToManyField(blank=True, related_name='organizaciones_org', to='Monitoreo.organizacion'),
        ),
    ]
