# Generated by Django 5.0 on 2024-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0021_alter_organismoexterno_lineas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='estaciones',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='sucursales',
        ),
        migrations.AlterField(
            model_name='organismoexterno',
            name='lineas',
            field=models.ManyToManyField(related_name='lineas_org', to='Monitoreo.lineatransporte'),
        ),
        migrations.AlterField(
            model_name='organismoexterno',
            name='organizaciones',
            field=models.ManyToManyField(related_name='organizaciones_org', to='Monitoreo.organizacion'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tipo_organizacion',
            field=models.CharField(choices=[('Supermercado', 'Supermercado'), ('Centro Comunal', 'Centro Comunal'), ('Banco', 'Banco'), ('Farmacia', 'Farmacia')], max_length=20),
        ),
    ]
